### ISSUE TITLE
ValueError: mutable default error

### ISSUE THREAD

**Issue by pwsnow** [cboddy/cycling-cadence-display#2]
Trying to run the program but getting the following error:

File "C:\Users\peter\AppData\Local\Programs\Python\Python311\Lib\dataclasses.py", line 815, in _get_field
raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'pandas.core.frame.DataFrame'> for field instant_rpm is not allowed: use default_factory

A quick look online states its an issue with 3.11 Python.

Has anyone else come across this?

**Comment by pwsnow** [comment]
Also for more information:

`Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\peter\AppData\Roaming\Python\Python311\Scripts\cycling_cadence_display.exe\__main__.py", line 4, in <module>
  File "C:\Users\peter\AppData\Roaming\Python\Python311\site-packages\cycling_cadence_display\app.py", line 28, in <module>
    @dataclass
     ^^^^^^^^^
  File "C:\Users\peter\AppData\Local\Programs\Python\Python311\Lib\dataclasses.py", line 1230, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "C:\Users\peter\AppData\Local\Programs\Python\Python311\Lib\dataclasses.py", line 1220, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\peter\AppData\Local\Programs\Python\Python311\Lib\dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\peter\AppData\Local\Programs\Python\Python311\Lib\dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'pandas.core.frame.DataFrame'> for field instant_rpm is not allowed: use default_factory`

**Comment by cboddy** [comment]
Hello, this is likely due to a change in a recent version of pandas, if you downgrade to v0.22.0 it should work. Otherwise feel free to open a PR to make it compatible with both versions, or pin the pandas dependency.

**Comment by ajd4096** [comment]
diff --git a/cycling_cadence_display/app.py b/cycling_cadence_display/app.py
index 7171ec9..624b333 100644
--- a/cycling_cadence_display/app.py
+++ b/cycling_cadence_display/app.py
@@ -2,7 +2,7 @@ import asyncio
 from bleak import BleakClient

 from pycycling.cycling_speed_cadence_service import CyclingSpeedCadenceService, CSCMeasurement
-from dataclasses import dataclass
+from dataclasses import dataclass, field
 import argparse
 import os
 import logging
@@ -35,8 +35,8 @@ class CycleContext:
     mean_rpm: str = "N/A"
     duration: str = "N/A"
     last_instant_rpm: str = "N/A"
-    measurements: pd.DataFrame = pd.DataFrame(columns=["cumulative_crank_revs", "last_crank_event_time"])
-    instant_rpm: pd.DataFrame = pd.DataFrame()
+    measurements: pd.DataFrame = field(default_factory = lambda: pd.DataFrame(columns=["cumulative_crank_revs", "last_crank_event_time"]))
+    instant_rpm: pd.DataFrame = field(default_factory = pd.DataFrame())

     def update(self, event: CSCMeasurement):
         cumulative_crank_revs = event.cumulative_crank_revs
